{% set name = "hstcal" %}
{% set version = "2.7.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/spacetelescope/hstcal/archive/refs/tags/{{ version }}.tar.gz
  sha256: d0ee879a3d7c07067c0148c360f13b90246d57d193add4bcf1642ad00bedd42a

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('fortran') }}
    - python
    - pkg-config
  host:
    - bzip2  # [linux]
    - libcurl  # [linux]
    - cfitsio
    - llvm-openmp  # [osx]
    - libgcc
    - _openmp_mutex  # [linux]

test:
  commands:
    - calacs.e --gitinfo

about:
  home: https://github.com/spacetelescope/hstcal
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: Calibration for HST/WFC3, HST/ACS, and HST/STIS
  doc_url: https://hstcal.readthedocs.io/
  dev_url: https://github.com/spacetelescope/hstcal

extra:
  recipe-maintainers:
    - jhunkeler
    - bgannon2
    - stsci-hack
    - mdlpstsci
    - nden
